server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: my-app-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: myapp
          __path__: /var/log/myapp/app.log

    pipeline_stages:
      - multiline:
          firstline: '^\d{4}-\d{2}-\d{2}' # multiline starts with a timestamp
          max_wait_time: 5s
          max_lines: 100
      - regex:
          expression: '^(?P<timestamp>\d+-\d+-\d+ \d+:\d+:\d+) \[(?P<level>\w+)] (?P<msg>.*)$'
      - output:
          source: msg
